spring:
 datasource:
    url: jdbc:mysql://localhost/algamoney_api
    username: danilo
    password: danilo@1      
        
 jpa:
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   generate-ddl: true
  # hibernate.ddl-auto: update
   show-sql: true

 jackson:    deserialization:      fail-on-unknown-properties: true 
      
 #flyway:
   #  baselineOnMigrate: true se ja houvessem tabelas

 security:
  oauth2:
   resourceserver:
    opaquetoken:
     introspection-uri: http://localhost:8080/oauth/check_token
     client-id: angular
     client-secret: angul@r0